export const FETCH_TODOS_COMPLETED = "FETCH_TODOS_COMPLETED"
export const FETCH_TODOS_START = "FETCH_TODOS_START"
export const FETCH_TODOS_ERROR = "FETCH_TODOS_ERROR"

export default {
    FETCH_TODOS_COMPLETED,
    FETCH_TODOS_START,
    FETCH_TODOS_ERROR
}