export const FETCH_TODOS_COMPLETED = "FETCH_TODOS_COMPLETED"
export const FETCH_TODOS_START = "FETCH_TODOS_START"
export const FETCH_TODOS_ERROR = "FETCH_TODOS_ERROR"

export const ADD_TODO_START = "ADD_TODO_START"
export const ADD_TODO_COMPLETED = "ADD_TODO_COMPLETED"
export const ADD_TODO_ERROR = "ADD_TODO_ERROR"

export const REMOVE_TODO_START = "REMOVE_TODO_START"
export const REMOVE_TODO_COMPLETED = "REMOVE_TODO_COMPLETED"
export const REMOVE_TODO_ERROR = "REMOVE_TODO_COMPLETED"

export const COMPLETE_TODO_START = "COMPLETE_TODO_START"
export const COMPLETE_TODO_COMPLETED = "COMPLETE_TODO_COMPLETED"
export const COMPLETE_TODO_ERROR = "COMPLETE_TODO_ERROR"


export default {
    FETCH_TODOS_COMPLETED,
    FETCH_TODOS_START,
    FETCH_TODOS_ERROR,
    ADD_TODO_START,
    ADD_TODO_COMPLETED,
    ADD_TODO_ERROR,
    REMOVE_TODO_START,
    REMOVE_TODO_COMPLETED,
    REMOVE_TODO_ERROR,
    COMPLETE_TODO_START,
    COMPLETE_TODO_COMPLETED,
    COMPLETE_TODO_ERROR
}